name: rawdrawandroid
on:
  push:
    branches:
      - '**' # All branches for now
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    # Can we do this without a custom "container:"?
    steps:
    - uses: actions/checkout@v2
    - name: Update packagedb
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y openjdk-11-jdk-headless adb
      #TODO install android deps
      #TODO make 

