name: rawdrawandroid
on:
  push:
    branches:
      - '**' # All branches for now
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    # Can we do this without a custom "container:"?
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies (apt)
      run: sudo apt-get install -y --no-install-recommends \
            build-essential \
            openjdk-11-jdk-headless \
            unzip \
            wget \
            zip \
            git \
            vim \
            gettext-base
    - env:
      ANDROID_HOME: /home/droid/android-sdk
      SDKMANAGER: $ANDROID_HOME/cmdline-tools/bin/sdkmanager
      TMPFILE: /home/droid/temp.zip
      URL_CLITOOLS: https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
      
    - name: Download Android tooling
      run: mkdir -p ${ANDROID_HOME} \
            && wget --quiet ${URL_CLITOOLS} -O ${TMPFILE} \
            && unzip -d ${ANDROID_HOME} ${TMPFILE} \
            && rm ${TMPFILE}
                  
    - name: Install Android tooling
      run: yes | $SDKMANAGER --sdk_root=${ANDROID_HOME} --licenses \
            && $SDKMANAGER --sdk_root=${ANDROID_HOME} \
                    "build-tools;29.0.3" \
                    "cmake;3.10.2.4988404" \
                    "ndk;22.1.7171670" \
                    "patcher;v4" \
                    "platform-tools" \
                    "platforms;android-30" \
                    "tools"
                    # This list can probably be reduced

    - name: Build APK
      run: cd rawdrawandroid && make keystore && make

